### ISSUE TITLE
Implement Docker compat api

### ISSUE THREAD

**Issue by vv9k** [vv9k/podman-api-rs#106]
## TODO:
...

https://docs.podman.io/en/latest/_static/api.html#tag/containers-(compat)

**Comment by vv9k** [comment]
I don't think it makes much sense to implement this on the client side so I'm gonna close this issue for now unless a reason for this to exist arises.

**Comment by NerdToMars** [comment]
we might need this for some security-opt

**Comment by NerdToMars** [comment]
perhaps https://github.com/fussybeaver/bollard if want to use compat api
