### ISSUE TITLE
Implement `events` endpoint

### ISSUE THREAD

**Issue by marhkb** [vv9k/podman-api-rs#109]
First, I would like to thank you for this project. I use it in my project, and it makes my life a lot easier.

Are there any plans to support the `events` endpoint in the future (https://docs.podman.io/en/latest/_static/api.html#operation/SystemEventsLibpod)? I have already seen #42, but there is no mention of the `System` API under which the endpoint can be found.

I think this would be an important feature to use podman-api-rs in user interfaces. That way, one wouldn't always have to poll for changes.

**Comment by vv9k** [comment]
Thank you for you kind words :)

The `events` endpoint is already implemented here https://docs.rs/podman-api/latest/podman_api/struct.Podman.html#method.events . All of the `system` endpoints are implemented on the `Podman` struct.
