### ISSUE TITLE
Deserialization error in `Containers::inspect` because `InspectNetworkSettings::ports` can have `null` values

### ISSUE THREAD

**Issue by marhkb** [vv9k/podman-api-rs#120]
This is similar to the issue #111 where the deserialization failed because 'InspectContainerHostConfig::port_bindings' could have `null` values. I just noticed that. Can be seen in this example [test_host-config_ports.json.zip](https://github.com/vv9k/podman-api-rs/files/8599552/test_host-config_ports.json.zip) (remove the .zip extension)

- Crate version: latest git
- OS: Linux
- Output of running `podman version` on the command line:
```
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.16.8
Built:        Wed Dec  8 22:45:07 2021
OS/Arch:      linux/amd64
```

**Comment by vv9k** [comment]
Thank you for the report! I pushed a temporary fix in 03de989 but will continue to look for a cleaner solution in #111.
