### ISSUE TITLE
Podman exec leaks conmon processes

### ISSUE THREAD

**Issue by MarkRx** [vv9k/podman-api-rs#130]
When running create_exec & exec.start() a conmon process is launched that does not terminate even after the command completes.

OS: RHEL 8.6
Podman: 4.0.2
Crate: 0.4.0

*Steps to Reproduce*
1. Launch an image in terminal mode to keep it running and obtain the image id
2. Compile and run the code below to exec a sleep every 5 seconds:

> ./podman_conmon <container_id>

3. Use ps -aux and observe that it is filled up with conmon processes:

> myuser 28551 0.0 0.0 143860 2452 ? Ssl 14:18 0:00 /usr/bin/conmon --api-version 1 -c e50b946b3bbee1cc1398d75d09a555bab6
> myuser 28583 0.0 0.0 143860 828 ? S 14:18 0:00 /usr/bin/conmon --api-version 1 -c e50b946b3bbee1cc1398d75d09a555bab6
> myuser 28586 0.0 0.0 143860 2420 ? Ssl 14:18 0:00 /usr/bin/conmon --api-version 1 -c e50b946b3bbee1cc1398d75d09a555bab6
> myuser 28617 0.0 0.0 143860 828 ? S 14:18 0:00 /usr/bin/conmon --api-version 1 -c e50b946b3bbee1cc1398d75d09a555bab6
> myuser 28622 0.0 0.0 143860 2484 ? Ssl 14:18 0:00 /usr/bin/conmon --api-version 1 -c e50b946b3bbee1cc1398d75d09a555bab6
> myuser 28658 0.0 0.0 143860 832 ? S 14:18 0:00 /usr/bin/conmon --api-version 1 -c e50b946b3bbee1cc1398d75d09a555bab6
> myuser 28660 0.0 0.0 143860 2336 ? Ssl 14:18 0:00 /usr/bin/conmon --api-version 1 -c e50b946b3bbee1cc1398d75d09a555bab6
> myuser 28692 0.0 0.0 143860 828 ? S 14:18 0:00 /usr/bin/conmon --api-version 1 -c e50b946b3bbee1cc1398d75d09a555bab6

4. Now use the podman CLI and observe that the conmon process is not leaked:

> podman exec <container_id> /usr/bin/sleep 5

```rust
use futures::StreamExt;
use podman_api::{Podman, conn::TtyChunk, opts::ExecStartOpts};

#[tokio::main]
async fn main() {
    let args: Vec<String> = env::args().collect();

    let podman = Podman::unix("/run/user/78572/podman/podman.sock");
    let container_id = &args[1];

    loop {
        let cmd = vec!["/usr/bin/sleep", "5"];

        let container = podman.containers().get(container_id);

        let res = container.create_exec(
            &podman_api::opts::ExecCreateOpts::builder()
                .command(cmd)
                .attach_stdout(true)
                .build(),
        ).await;

        let exec = res.unwrap();
        
        let opts = ExecStartOpts::default();
        let mut stream  = exec.start(&opts);
        while let Some(chunk) = stream.next().await {
            if let Ok(msg) = chunk {
                match msg {
                    TtyChunk::StdOut(message) => {
                        let str = String::from_utf8_lossy(&message);
                        println!("stdout [{}]: {}", container_id, str);
                    },
                    _default => {  }
                }
            }
        }
    }
}
```

Cargo.toml:
```
[package]
name = "podman_conmon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bollard = "0.13.0"
futures = "0.3.21"
podman-api = "0.4"
tokio = { version = "1.19.2", features = ["macros", "process", "rt-multi-thread", "sync"] }
```

**Comment by MarkRx** [comment]
This may be an issue with podman itself. See https://github.com/containers/podman/issues/15377

**Comment by vv9k** [comment]
Thanks for the report. As @mheon noted in the upstream issue, this is a hack in podman so I'm going to close this issue as it doesn't happen in this crate.

> This is deliberate, if a bit of an ugly hack. Basically, Podman needs to retain the exec session in the database for 5 minutes after it exits for Docker compat. We don’t have a daemon, so the easiest way to do this is to have Conmon wait 5 minutes before cleaning up the database and exiting.
> 
> I hope to remove the need for this in the future when we move to Conmon-rs.
