### ISSUE TITLE
Regression in constructing JSON filters

### ISSUE THREAD

**Issue by marhkb** [vv9k/podman-api-rs#131]
For example, a deserialized container filter now looks like
```json
{"id":["id=0c24b5b39bab46f79c7b763a21f4562692400af0963e4e82d2f4d58c4e1aaffa"]}
```
But it should look like
```json
{"id":["i0c24b5b39bab46f79c7b763a21f4562692400af0963e4e82d2f4d58c4e1aaffa"]}
```

So, if we URL encode the first JSON, we don't retrieve any containers
```shell
$ curl --unix-socket /run/user/1000/podman/podman.sock http://d/v3.0.0/libpod/containers/json\?all\=true\&filters=%7B%22id%22%3A%5B%22id%3Da9ee744d373ad80a280f66cb3fdcd443b9320482ce1d32c9999c3ae1806116d5%22%5D%7D
[]
```
If we remove the `id=` part, we retrieve the correct result.
```shell
$ curl --unix-socket /run/user/1000/podman/podman.sock http://d/v3.0.0/libpod/containers/json\?all\=true\&filters=%7B%22id%22%3A%5B%220c24b5b39bab46f79c7b763a21f4562692400af0963e4e82d2f4d58c4e1aaffa%22%5D%7D
[{"AutoRemove":false,"Command":["mongod"],"Created":"2022-08-27T21:10:48.274351047+02:00","CreatedAt":"","Exited":false,"ExitedAt":-62135596800,"ExitCode":0,"Id":"0c24b5b39bab46f79c7b763a21f4562692400af0963e4e82d2f4d58c4e1aaffa","Image":"docker.io/library/mongo:latest","ImageID":"a3c1334134aafd75500fbfe5cddbc0bde4d628725cb074bf988edbbad2cf0acc","IsInfra":false,"Labels":null,"Mounts":["/data/configdb","/data/db"],"Names":["TEST_PODMAN_API_RS"],"Namespaces":{},"Networks":[],"Pid":709080,"Pod":"","PodName":"","Ports":[{"host_ip":"","container_port":27017,"host_port":27017,"range":1,"protocol":"tcp"}],"Size":null,"StartedAt":1661627448,"State":"running","Status":"healthy"}]

```

- Crate version: 0.5.0 (9d02f4b60d3129ca7d2291e30d0f4136e5d9a1da)
- OS: 5.18.18-200.fc36.x86_64 SMP PREEMPT_DYNAMIC Wed Aug 17 16:02:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Output of running `podman version` on the command line:
```
Client:       Podman Engine
Version:      4.2.0
API Version:  4.2.0
Go Version:   go1.18.4
Built:        Thu Aug 11 16:42:17 2022
OS/Arch:      linux/amd64
```

**Comment by vv9k** [comment]
Fixed this in https://github.com/vv9k/containers-api/commit/e407b14c671253eb53a49c2370a685d0c1df6a94 and added tests to prevent future regressions https://github.com/vv9k/containers-api/commit/ca80b56aa8de7a9066e97d718bb90ec5433db733 .

I was wondering how to handle the `label!=key=value` filters and it turns out the key in the map has to be `label!` for this to work, so my concept made no sense. More info about this filters here: https://github.com/containers/podman/issues/13270

**Comment by marhkb** [comment]
Thanks. This fixes it for me.
