### ISSUE TITLE
How to support Send

### ISSUE THREAD

**Issue by arlyon** [vv9k/podman-api-rs#137]
Hi! I am looking to use this library with a threadpool and am running into problems because most of the API is not Send. I wanted to open this issue up to see what your opinions are.

**Comment by vv9k** [comment]
Hey! Thanks for you interest in `podman-api-rs`:)

The version `0.6.0` accidentally removed `Send` and `Sync` impls from futures returned by api endpoints. To resolve the issue try using version `0.7.0` that just got published (I tagged it but forgot to publish to crates.io) or the master branch:
```
podman-api = "0.7"
# or
podman-api = { git = "https://github.com/vv9k/podman-api-rs" }
```

**Comment by arlyon** [comment]
Looks like this is working for me on 0.7, thanks for your work :)
