### ISSUE TITLE
400 Bad Request on Wait for Running

### ISSUE THREAD

**Issue by atagen** [vv9k/podman-api-rs#160]
Hello,

- Crate version: 10.0.0
- OS: Linux (NixOS 23.05 Unstable/Fedora 36)
- Output of running `podman version` on the command line:
```
Client:       Podman Engine
Version:      4.5.0
API Version:  4.5.0
Go Version:   go1.20.4
Built:        Tue Jan  1 11:00:00 1980
OS/Arch:      linux/amd64
```

The following code:
```rs
podman.containers().get(&some_ctr_id).wait(
    &ContainerWaitOpts::builder()
        .interval("500ms")
        .conditions([ContainerStatus::Running, ContainerStatus::Exited])
        .build(),
).await?;
```
results in the output:
```
error 400 Bad Request - failed to parse parameters for /v4.3.1/libpod/containers/3c682f2314e885205fcec77af539fe55f94a61f7d44793119ee66aa226acf73f/wait?condition=%5B%22running%22%5D&interval=500ms: schema: error converting value for index 0 of "condition": schema: error converting value for index 0 of "condition"
```

The code 
```rs
println!(self.podman.info().await?.version.unwrap().api_version.unwrap());
```
prints "4.5.0" as expected.

However, it appears that:
- API version being called (v4.3.1) is wrong for my version of podman, and inconsistent with reported values
- "Running" is not a valid value here in the API, despite the Podman docs reporting that it is
- Using `adjust_api_version()` or `new_versioned()` has identical results, except for the API versions chosen by the client (1.41 and 4.5.0 instead of 4.3.1).
- This only happens with Running status, other statuses work fine
- This isn't caught by tests as there is no test for the `wait` command

Calling `podman wait some_container --condition running` from the CLI works as expected.

Please let me know if there's any further information or testing I can provide, or if there's somewhere I could start looking to fix this - I would very much like to get this working.

Thanks :)

**Comment by vv9k** [comment]
Thanks for spotting this! There was a problem with how the `ContainerWaitOpts::conditions` parameter was serialized and it doesn't matter which version you are using. I've create a PR #161 that fixes the issue and adds a test case for `Container::wait`. Tested locally with version 4.5.0 and before the changes it failed with the error you provided, now the test case works.

**Comment by atagen** [comment]
Fix works, perfect! Thanks for being so quick :)
