### ISSUE TITLE
PreCheckpoint support

### ISSUE THREAD

**Issue by antoniocalagna98** [vv9k/podman-api-rs#163]
Hi everyone!

Thank you very much for the excellent work you have been doing.

I found out that some booleans for the ContainerCheckpointOptions are missing, namely, "PreCheckpoint" and "withPrevious".

These were introduced in the official LibPod APIs starting from version 4.3 (see [Checkpoint API](https://docs.podman.io/en/latest/_static/api.html#tag/containers/operation/ContainerCheckpointLibpod))

Thank you in advance for your time.

**Comment by vv9k** [comment]
Hello!

Thanks for your report. I've added missing options in #164, hope it resolves your issues.
